export const Communes = [
    { name: 'Renca', number: '1', zone: 1, },
    { name: 'Conchalí', number: '2', zone: 1, },
    { name: 'Recoleta', number: '3', zone: 1, },
    { name: 'Independencia', number: '4', zone: 1, },
    { name: 'Las Condes', number: '5', zone: 1, },
    { name: 'Vitacura', number: '6', zone: 1, },
    { name: 'La Reina', number: '7', zone: 1, },
    { name: 'Peñalolen', number: '8', zone: 1, },
    { name: 'Providencia', number: '9', zone: 1, },
    { name: 'Santiago Centro', number: '10', zone: 1, },
    { name: 'Ñuñoa', number: '11', zone: 1, },
    { name: 'Macul', number: '12', zone: 1, },
    { name: 'San Miguel', number: '13', zone: 1, },
    { name: 'San Joaquin', number: '14', zone: 1, },
    { name: 'Cerro Navia', number: '15', zone: 1, },
    { name: 'Quinta Normal', number: '16', zone: 1, },
    { name: 'Lo Prado', number: '17', zone: 1, },
    { name: 'Estación Central', number: '18', zone: 1, },
    { name: 'Pedro Aguirre Cerda', number: '19', zone: 1, },
    { name: 'Cerrillo', number: '20', zone: 1, },
    { name: 'Lo Espejo', number: '21', zone: 1, },
    { name: 'La Cisterna', number: '22', zone: 1, },
    { name: 'San Ramón', number: '23', zone: 1, },
    { name: 'La Granja', number: '24', zone: 1, },
    { name: 'La Florida', number: '25', zone: 1, },
    { name: 'El Bosque', number: '26', zone: 1, },
    { name: 'La Pintana', number: '27', zone: 1, },
    { name: 'Maipú', number: '28', zone: 1, },
    { name: 'Puente Alto', number: '29', zone: 1, },

    { name: 'Quilicura', number: '30', zone: 2, },
    { name: 'Colina, Chicureo', number: '31', zone: 2, },
    { name: 'Huechuraba', number: '32', zone: 2, },
    { name: 'Pudahuel, Pudahuel Sur, Ciudad de los Valles', number: '33', zone: 2, },
    { name: 'San Bernardo', number: '34', zone: 2, },
    { name: 'Padre Hurtado', number: '35', zone: 2, },
    { name: 'Lampa, Valle Grande y Chicauma', number: '36', zone: 2, },
    { name: 'Peñaflor', number: '37', zone: 2, },
    { name: 'Talagante', number: '38', zone: 2, },
    { name: 'Calera de Tango', number: '39', zone: 2, },
    { name: 'Lo Barnechea', number: '40', zone: 2, },
]