export enum Days {
  SUNDAY = 'DOMINGO',
  MONDAY = 'LUNES',
  TUESDAY = 'MARTES',
  WEDNESDAY = 'MIÉRCOLES',
  THURSDAY = 'JUEVES',
  FRIDAY = 'VIERNES',
  SATURDAY = 'SÁBADO',
  ALL="TODOS LOS DÍAS",
  MondaytoFriday="LUNES - VIERNES"
}
